on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: "ramsey/composer-install@v2"
      with:
        dev: yes
        args: --profile --ignore-platform-reqs
        php_version: "7.4"
        
    - name: Update dependencies
      uses: "ramsey/composer-update@v2"
      with:
        dev: yes
        args: --profile --ignore-platform-reqs
        php_version: "7.4"
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: production/